name: neurosynk
description: Smartwatch-Powered Heart Health Monitoring App

# App version
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296

  # State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

  # Data Visualization
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^22.2.5

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0

  # Networking & API
  http: ^1.1.0
  dio: ^5.3.0
  socket_io_client: ^2.0.3+1

  # Bluetooth Low Energy
  flutter_blue_plus: ^1.14.6
  permission_handler: ^11.0.1

  # Authentication
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3

  # JSON & Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Date & Time
  intl: ^0.18.1
  timezone: ^0.9.2

  # Device Info
  device_info_plus: ^9.1.0
  package_info_plus: ^4.1.0

  # File Handling
  path_provider: ^2.1.1
  csv: ^5.0.2

  # Notifications
  flutter_local_notifications: ^15.1.1
  awesome_notifications: ^0.7.4+1

  # Security
  flutter_secure_storage: ^9.0.0

  # Utils
  uuid: ^3.0.7
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  hive_generator: ^2.0.0

  # Linting
  flutter_lints: ^2.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600